#ifndef PLAYTOGETHER_CONSTANTS_H
#define PLAYTOGETHER_CONSTANTS_H

#define TRUE 1
#define FALSE 0

#define SUCCESS 1
#define LOADING 0
#define FAILURE -1


//ACTIONS
#define PLAY "ACTION_PLAY\r\n"
#define PAUSE "ACTION_PAUSE\r\n"
#define SEEK_FORWARD "ACTION_SEEK_FORWARD\r\n"
#define SEEK_BACKWARD "ACTION_SEEK_BACKWARD\r\n"
#define SERVER_STOP "ACTION_SERVER_STOP\r\n"

#define GET_SEEK "GET_SEEK"
#define SET_SEEK "SET_SEEK"

#endif
